### ISSUE TITLE
Cast Exception in Jenkins 1.580.3

### ISSUE THREAD

**Issue by martin1yness** [achikin/testrail-jenkins-plugin#2]
I attempted to install this plugin but received the following error during build execution:

<pre>
Munging test result files.
Scanning C:\Users\ADMINI~1\AppData\Local\Temp\hudson1280848565691490540tmp
processing hudson1280848565691490540tmp
processing TEST-WebInstallerTest.xml
ERROR: Publisher testrail.testrail.TestRailNotifier aborted due to exception
java.lang.ClassCastException: testrail.testrail.JunitResults.Testsuite cannot be cast to testrail.testrail.JunitResults.Testsuites
    at testrail.testrail.JunitResults.JUnitResults$1$1.visit(JUnitResults.java:68)
    at hudson.util.DirScanner.scanSingle(DirScanner.java:49)
    at hudson.util.DirScanner$Glob.scan(DirScanner.java:131)
    at testrail.testrail.JunitResults.JUnitResults$1.invoke(JUnitResults.java:62)
    at testrail.testrail.JunitResults.JUnitResults$1.invoke(JUnitResults.java:58)
    at hudson.FilePath.act(FilePath.java:980)
    at hudson.FilePath.act(FilePath.java:958)
    at testrail.testrail.JunitResults.JUnitResults.slurpTestResults(JUnitResults.java:58)
    at testrail.testrail.JunitResults.JUnitResults.<init>(JUnitResults.java:47)
    at testrail.testrail.TestRailNotifier.perform(TestRailNotifier.java:117)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
    at hudson.model.Run.execute(Run.java:1770)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
</pre>

**Comment by xirsoi** [comment]
@martin1yness , are you still experiencing this issue?

**Comment by martin1yness** [comment]
Ended up forking project so not sure if this defect still exists in this version.
